### PR TITLE
Add zoxide under Shell Plugins

### PR DESCRIPTION
**Pull request by ajeetdsouza**
[zoxide](https://github.com/ajeetdsouza/zoxide) is meant to be an improved z:

- Added features, eg. autocomplete and fzf integration
- An improved algorithm (in my opinion)
- More customizability
- Better performance
- Cross-shell compatibility, works on 8 shells and counting
- Plugins for other CLI tools, like vim/emacs/ranger/nnn/etc.

Closes https://github.com/trimstray/the-book-of-secret-knowledge/issues/206.

### CODE REVIEW

**Comment by 0-pt1mu5** [comment]
Add shell into C://User'path', then launch the Java plugin

**Review by Shivam602 — COMMENTED** [review]
- ty

**Comment by loukia23** [comment]
Ty

**Comment by ajeetdsouza** [comment]
Hey @trimstray, sorry to see this could not be merged. I'd appreciate any feedback you have about zoxide, if you can spare the time!

**Pull request closed without merging**
