### PR TITLE
sterilize shell history

### PR DESCRIPTION
**Pull request by lbonanomi**
### Please review carefully, I am no one's security specialist.

A shell function to help bash's history "forget" curl and wget commands with inline passwords.

Define this function in a user init file such as .bash_profile and have it executed after every command by adding it to an exported PROMPT_COMMAND variable.

### CODE REVIEW

**Comment by trimstray** [comment]
It looks interesting and... works. I accept this PR as a good introduction to possible modification.

**Comment by lbonanomi** [comment]
Please do modify this! 

The rules are skeletal because curl and wget are what most frequently embarrassed myself with when su'ed into a shared account.

It seemed to fit the spirit of the repo to do this with common shell tools, but an implementation in another language would certainly be a good idea.

**Comment by trimstray** [comment]
@lbonanomi : ok, in my free time I'll modify it (or I'll find an alternative solution) but in this form it is a good basis for modification by others before enable it.

**Comment by lbonanomi** [comment]
You were right, this was better in a fuller-language.

https://github.com/lbonanomi/go/blob/master/revisionist.go

**Comment by trimstray** [comment]
@lbonanomi : nice, I added this to repo.

**Pull request merged**
