### PR TITLE
update link

### PR DESCRIPTION
**Pull request by abe-101**
per the subreddit https://www.reddit.com/r/privacytoolsIO/ the
maitainers have moved to the new domain https://privacyguides.org/

https://www.reddit.com/r/privacytoolsIO/comments/pnql46/rprivacyguides_privacyguidesorg_what_you_need_to/

- signed-off-by: Abe <abe@habet.dev>

### CODE REVIEW

**Comment by abe-101** [comment]
There seems to be little bit of controversy behind this story. Based on my understanding the owner of the site privacytools.io wasn't responding to the maintainers. Forcing the maintainers to rebrand. Although the link privacytools.io isn't broken, it seems that privacyguides.org has more relevant and updated information

**Comment by abe-101** [comment]
IntelTechniques is no longer a mass scanner
* signed-off-by: Abe abe@habet.dev

**Review by Sleekbobby1011 — APPROVED** [review]

**Review by Kausaselite — APPROVED** [review]
- ```

```

**Comment by AaronJD95** [comment]
Unsubscribe

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Plusheaven** [comment]
Sideways day 🤣 today is a sideways day

**Comment by Rinat198** [comment]
README.md

**Review by Sleekbobby1011 — APPROVED** [review]

**Comment by Rinat198** [comment]
README.md

**Comment by Rinat198** [comment]
> README.md

**Comment by Plusheaven** [comment]
Sideways day is a great understatement *_****_Krypto_Kevin**

**Comment by Plusheaven** [comment]
Have over 5582 hours of study in BTC 💯 and ALT Coins for further gains in a struggling market.
Blockchain technology is going to take off just don't know when it will be incorporated into everyday life 🧬

**Review by edgarelsalto — APPROVED** [review]
Gracias

**Review by Princeprince559 — APPROVED** [review]
It's a go I guess

**Review by FukYaMudda — APPROVED** [review]

**Review by FukYaMudda — APPROVED** [review]

**Review by FukYaMudda — APPROVED** [review]

**Review by FukYaMudda — APPROVED** [review]

**Review by FukYaMudda — APPROVED** [review]

**Review by FukYaMudda — APPROVED** [review]

**Review by whiteGo41745617 — CHANGES_REQUESTED** [review]
whitegoldagency7@github.com it account setting email phone number SIM card for register question security strong password auto complease finish find to register question security strong password fomus pin lockin only one by security update change save for any years for highway drive to only me see with drive to Google play balance money all to buckup download update save

**Comment by Plusheaven** [comment]
When

**Comment by Plusheaven** [comment]
Going to school now for Network engineering anything to do with wire or wireless for now

**Comment by TalleA15** [comment]
Leaning may things @NlTDA Blockchain 
an experience which l have never  come across in life ****

**Comment by TalleA15** [comment]
#

**Pull request closed without merging**
