### PR TITLE
Merge pull request #127 from pstavirs/osti

### PR DESCRIPTION
**Pull request by pstavirs**
Ostinato is a Packet Crafter and Traffic Generator

_Disclosure_: I'm the author of this tool. Feel free to evaluate it before you add. The [Ostinato project](https://github.com/pstavirs/ostinato) is open-source but binaries are paid to help sustain the project.

### CODE REVIEW

**Comment by pstavirs** [comment]
Just checking in to see if I can help somehow to move this PR forward?

**Comment by trimstray** [comment]
> Older versions are available in the release archives (Windows, MacOS, Linux) - some for free. Source code at GitHub.

The newest release is not free?

**Comment by pstavirs** [comment]
@trimstray Source code for all releases - old or new - is free. See [Ostinato Releases](https://github.com/pstavirs/ostinato/releases).

> Older versions are available in the release archives (Windows, MacOS, Linux) - some for free.

The above statement from ostinato.org pertains to compiled binaries. Binary for newest release is available for a small fee. Source code is still free - you can build from source and not pay anything if you want. Payment in exchange for binaries is to help sustain the project.

**Comment by trimstray** [comment]
@pstavirs : ok, thanks for explain this, added :+1:

**Pull request merged**
