### PR TITLE
Update the Broken Link with new one

### PR DESCRIPTION
**Pull request by EzzOps**

### CODE REVIEW

**Review by tihannalouise — CHANGES_REQUESTED** [review]
Change back

**Review by Akaedes — APPROVED** [review]

**Review by Bmaziarz1966 — APPROVED** [review]

**Review by CrazyJewel — CHANGES_REQUESTED** [review]
I didn't request this!

**Comment by TalleA15** [comment]
Change it I'm a student just learning

**Review by sandra380 — APPROVED** [review]

**Review by abhishek-kr-1 — APPROVED** [review]

**Comment by kkovaletp** [comment]
"The NRE Labs project has shut down, and the interactive labs are no longer available. See [this blog post](https://nrelabs.io/2021/12/goodbye-for-now/) for more information." - this is the banner on top of their site. So, it's maybe better to remove the entry completely.

**Review by skydiver1980 — APPROVED** [review]

**Review by Maxienite — APPROVED** [review]

**Pull request closed without merging**
