### PR TITLE
Add mssql-cli

### PR DESCRIPTION
**Pull request by Meir017**

### CODE REVIEW

**Comment by Asesuas** [comment]
> ## []()``

**Comment by FITOLOPEUNSOIX** [comment]
.l

**Review by bobcampbell112233 — COMMENTED** [review]
Very good idea

**Comment by Ally6981** [comment]
What is

**Review by Scutua — APPROVED** [review]

**Review by lopezregalodelo-a11y — COMMENTED** [review]
Updated

**Review by lopezregalodelo-a11y — APPROVED** [review]
Update

**Review by lopezregalodelo-a11y — CHANGES_REQUESTED** [review]
Updated

**Pull request merged**
