### PR TITLE
Merge pull request #146 from pylipp/fix/remove-duplicate

### PR DESCRIPTION
**Pull request by pylipp**
Use description from NerdyData.com's homepage subtitle instead

### CODE REVIEW

**Comment by trimstray** [comment]
Thanks! :1st_place_medal:

**Review by Jcharly412 — COMMENTED** [review]
Level check

**Comment by Jcharly412** [comment]
2022

**Comment by Cjoe7989** [comment]
Fg
README.md


2022

-- 
Reply to this email directly or view it on GitHub:
https://github.com/trimstray/the-book-of-secret-knowledge/pull/146#issuecomment-1173357544
You are receiving this because you are subscribed to this thread.

Message ID: 
***@***.***>

Sent with Aqua Mail for Android
https://www.aqua-mail.com

**Review by gtganky — COMMENTED** [review]
[xalan -dev]java c/++ xalan-j-users

**Review by Henko551 — APPROVED** [review]

**Pull request merged**
