### PR TITLE
Create SECURITY.md

### PR DESCRIPTION
**Pull request by AR-sslink**

### CODE REVIEW

**Review by HONESTYISMYWORLD2 — APPROVED** [review]

**Review by AusArnon — APPROVED** [review]

**Comment by Swapnarajkumari** [comment]
I agree

**Comment by Swapnarajkumari** [comment]
What is this

**Comment by Stella911** [comment]
https://x.com/dian_tong9798?t=JREjVoY_-A_Yb3Gzq4Xwqg&s=09

**Review by HONESTYISMYWORLD2 — APPROVED** [review]
I didn't make changes until now

**Comment by 0979327380** [comment]
Dyng

**Review by Aarush-ICEMAN — APPROVED** [review]

**Comment by deecdub** [comment]
Hmmm, I hate myself

**Comment by Panellonepelatone** [comment]
Why tho

**Review by User1pf — APPROVED** [review]

**Review by unknown192 — APPROVED** [review]

**Review by skydiver1980 — APPROVED** [review]

**Pull request closed without merging**
