### PR TITLE
feat: add cognito-scanner pentest tool

### PR DESCRIPTION
**Pull request by cfpadok**
Cognito Scanner is a CLI open-source tool. It enables to pentest Cognito AWS instance easily. It can be installed through a python package. It could be a good tool to record to contribute to this repository.

Disclaimer : I am one of the developer of the tool

### CODE REVIEW

**Comment by TalleA15** [comment]
Good morning sir, a student learning, l have been blocked can't move an inch pls needed your guidance thanks

**Comment by TalleA15** [comment]
Pls tell me what to do ? How and where?  I

**Comment by nusair00** [comment]
i will help you

**Review by Davcob77 — APPROVED** [review]
Approve

**Comment by mololfyfyffhcjydutyhdsrtygfy** [comment]
hi sir

**Review by Davcob77 — APPROVED** [review]

**Comment by TalleA15** [comment]
Thankis,and remain Blessed

**Comment by RahulSahPhakir** [comment]
Send you vija.

**Comment by TalleA15** [comment]
Good day sir,  l want to unsubscribe this  all this pen test pls tell  me lm novice

**Review by Flaxpicker42 — APPROVED** [review]

**Review by Davcob77 — APPROVED** [review]

**Review by Davcob77 — APPROVED** [review]

**Review by Davcob77 — APPROVED** [review]

**Review by DonkyFab — APPROVED** [review]

**Comment by Stella911** [comment]
Hacker game, blog x 我曾利用天使 搜尋

**Comment by Stella911** [comment]
You have to pay the price. Hack them, my kin relative to 賣淫 bring wealth, 雄女學生與國防部,砍頭行動operating, please join. 

JUST INCASE I DIED FIRST PRINCE CHARMING 

And also guys kill them你沒辦法 








☺️

**Comment by Stella911** [comment]
You have to pay the price. Hack them, my kin☺️ relative to 賣淫 bring wealth, 雄女學生與國防部,砍頭行動operating, please join. 

JUST INCASE I DIED FIRST PRINCE CHARMING 

And also guys kill them你沒辦法 







decrypt the codes including 老母 
One day I will speak ten languages to tell the world 賣淫組織已經被根除了

**Comment by dhruvil677** [comment]
Hi sir.

**Comment by itsover8000** [comment]
Hi

**Review by Davcob77 — APPROVED** [review]

**Comment by L-uz** [comment]
Make sasta chat gtp

**Review by skydiver1980 — APPROVED** [review]

**Pull request closed without merging**
